export const MINIMUM_TAX_OPTIONS = [
  "DHAKA_/_CHATTOGRAM_CITY_CORPORATION_AREA",
  "OTHER_CITY_CORPORATION_AREA",
  "OTHER_AREA",
];

export const NET_WEALTH_SURCHARGE_OPTIONS = ["YES", "NO"];

export const REPAIR_COLLECTION_OPTIONS = [
  "COMMERCIAL_PROPERTY",
  "NON_-COMMERCIAL",
  "RESIDENTIAL_PROPERTY",
  "MIXED_PROPERTY",
];
