"use server"

import prisma from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import {
  IndividualTaxReturnFormInput,
  individualTaxReturnSchema,
} from "./schema";


export async function createIndividualTaxReturn(data: IndividualTaxReturnFormInput) {
  try {
    const validatedData = individualTaxReturnSchema.parse(data);

    const createIndividualTaxReturn = await prisma.individualTaxes.create({
      data: {
        userId: data.userId ??"",
        taxpayerName: data.taxpayerName,
        nationalId: data.nationalId,
        tin: data.tin,
        circle: data.circle,
        zone: data.zone,
        residentialStatus: data.residentialStatus,
        specialBenefits: data.specialBenefits,
        isParentOfDisabledPerson: data.isParentOfDisabledPerson,
        dateOfBirth: data.dateOfBirth.toISOString(),
        spouseName: data.spouseName,
        spouseTin: data.spouseTin,
        addressLine1: data.addressLine1,
        addressLine2: data.addressLine2,
        telephone: data.telephone,
        mobile: data.mobile,
        email: data.email,
        employerName: data.employerName,
        businessName: data.businessName,
        bin: data.bin,
        partnersInfo: data.partnersInfo,

        partnersMembersAssociation1: data.partnersMembersAssociation1,
        partnersMembersAssociation2: data.partnersMembersAssociation2,
        incomeYearEndedOn: data.incomeYearEndedOn,
        incomeFishFarming: data.incomeFishFarming,
        incomeFishFarmingAmount: data.incomeFishFarmingAmount,
        shareOfIncomeFromAOP: data.shareOfIncomeFromAOP,
        incomeOfMinor: data.incomeOfMinor,
        taxableIncomeFromAbroad: data.taxableIncomeFromAbroad,
        minimumTax: data.minimumTax,
        netWealthSurcharge: data.netWealthSurcharge,
        environmentalSurcharge: data.environmentalSurcharge,
        delayInterest: data.delayInterest,
        calculate: data.calculate,
        advanceTaxPaidAmount: data.advanceTaxPaidAmount,
        adjustmentOfTaxRefund: data.adjustmentOfTaxRefund,
        taxPaidWithThisReturn: data.taxPaidWithThisReturn,
        listOfDocumentsFurnishedWithThisReturn1: data.listOfDocumentsFurnishedWithThisReturn1,
        listOfDocumentsFurnishedWithThisReturn2: data.listOfDocumentsFurnishedWithThisReturn2,
        fatherOrHusband: data.fatherOrHusband,
        placeOfSignature: data.placeOfSignature,
        signature: data.signature,
        dateOfSignature: data.dateOfSignature.toISOString(),     
        locationDescriptionOwnershipProportionOfProperty: data.locationDescriptionOwnershipProportionOfProperty,
        rentReceivedOrAnnualValue: data.rentReceivedOrAnnualValue,
        advanceRentReceived: data.advanceRentReceived,
        valueOfAnyBenefit: data.valueOfAnyBenefit,
        adjustedAdvanceRent: data.adjustedAdvanceRent,
        vacancyAllowance: data.vacancyAllowance,
        repairCollection: data.repairCollection,
        municipalOrLocalTax: data.municipalOrLocalTax,
        landRevenue: data.landRevenue,
        interestMortgageCapitalCharge: data.interestMortgageCapitalCharge,
        insurancePremiumPaid: data.insurancePremiumPaid,
        others: data.others,
        taxpayersShare: data.taxpayersShare,
        taxDeductedSourceFromIncomeRent: data.taxDeductedSourceFromIncomeRent,
        salesTurnoverReceipt: data.salesTurnoverReceipt,
        grossProfit: data.grossProfit,
        generalExpensesSellingExpenses: data.generalExpensesSellingExpenses,
        nameOfBusiness: data.nameOfBusiness,
        natureOfBusiness: data.natureOfBusiness,
        addressOfBusiness: data.addressOfBusiness,
        salesTurnoverReceipts: data.salesTurnoverReceipt,
        grossProfitAmount: data.grossProfitAmount,
        generalAdministrativeSellingExpenses: data.generalAdministrativeSellingExpenses,
        badDebtExpense: data.badDebtExpense,
        inventories: data.inventories,
        fixedAssets: data.fixedAssets,
        otherAssets: data.otherAssets,
        openingCapital: data.openingCapital,
        withdrawalsInTheIncomeYear: data.withdrawalsInTheIncomeYear,
        liabilities: data.liabilities,
        interestProfitFromBankFIAmount: data.interestProfitFromBankFIAmount,
        interestProfitFromBankFIDeductions: data.interestProfitFromBankFIDeductions,
        interestProfitFromBankFITax: data.interestProfitFromBankFITax,
        incomeFromSavingCertificatesAmount: data.incomeFromSavingCertificatesAmount,
        incomeFromSavingCertificatesDeductions: data.incomeFromBusinessDeductions,
        incomeFromSavingCertificatesTax: data.incomeFromSavingCertificatesTax,
        incomeFromSecuritiesDebenturesAmount: data.incomeFromSecuritiesDebenturesAmount,
        incomeFromSecuritiesDebenturesDeductions: data.incomeFromSecuritiesDebenturesDeductions,
        incomeFromSecuritiesDebenturesTax: data.incomeFromSecuritiesDebenturesTax,
        incomeFromFinancialProductSchemeAmount: data.incomeFromFinancialProductSchemeAmount,
        incomeFromFinancialProductSchemeDeductions: data.incomeFromFinancialProductSchemeDeductions,
        incomeFromFinancialProductSchemeTax: data.incomeFromFinancialProductSchemeTax,
        dividendIncomeAmount: data.dividendIncomeAmount,
        dividendIncomeDeductions: data.dividendIncomeDeductions,
        dividendIncomeTax: data.dividendIncomeTax,
        capitalGainFromTransferOfPropertyAmount: data.capitalGainFromTransferOfPropertyAmount,
        capitalGainFromTransferOfPropertyDeductions: data.capitalGainFromTransferOfPropertyDeductions,
        capitalGainFromTransferOfPropertyTax: data.capitalGainFromTransferOfPropertyTax,
        incomeFromBusinessAmount: data.incomeFromBusinessAmount,
        incomeFromBusinessDeductions: data.incomeFromBusinessDeductions,
        incomeFromBusinessTax: data.incomeFromBusinessTax,
        workersParticipationFundAmount: data.workersParticipationFundAmount,
        workersParticipationFundDeductions: data.workersParticipationFundDeductions,
        workersParticipationFundTax: data.workersParticipationFundTax,
        incomeFromOtherSourcesAmount: data.incomeFromOtherSourcesAmount,
        incomeFromOtherSourcesDeductions: data.incomeFromOtherSourcesDeductions,
        incomeFromOtherSourcesTax: data.incomeFromOtherSourcesTax,
        lifeInsurancePremium: data.lifeInsurancePremium,
        contributionToDeposit: data.contributionToDeposit,
        investmentInGovernmentSecurities1: data.investmentInGovernmentSecurities1,
        investmentInGovernmentSecurities2: data.investmentInGovernmentSecurities2,
        investmentInSecurities: data.investmentInSecurities,
        contributionToProvidentFund: data.contributionToProvidentFund,
        selfAndEmployersContribution: data.selfAndEmployersContribution,
        contributionToSuperAnnuationFund: data.contributionToSuperAnnuationFund,
        contributionToBenevolentFund: data.contributionToBenevolentFund,
        contributionToZakatFund1: data.contributionToZakatFund1,
        contributionToZakatFund2: data.contributionToZakatFund2,
        othersIf1: data.othersIf1,
        othersIf2: data.othersIf2,
        expensesForFoodAmount: data.expensesForFoodAmount,
        expensesForFoodComment: data.expensesForFoodComment,
        housingExpenseAmount: data.housingExpenseAmount,
        housingExpenseComment: data.housingExpenseComment,
        personalTransportationExpensesAmount: data.personalTransportationExpensesAmount,
        personalTransportationExpensesAmountComment: data.personalTransportationExpensesAmountComment,
        utilityExpenseAmount: data.utilityExpenseAmount,
        utilityExpenseComment: data.utilityExpenseComment,
        educationExpensesAmount: data.educationExpensesAmount,
        educationExpensesComment: data.educationExpensesComment,
        personalExpenseAmount: data.personalExpenseAmount,
        personalExpenseComment: data.personalExpenseComment,
        festivalExpenseAmount: data.festivalExpenseAmount,
        festivalExpenseComment: data.festivalExpenseComment,
        taxDeductedAmount: data.taxDeductedAmount,
        taxDeductedComment: data.taxDeductedComment,
        advanceTaxPaid2Amount: data.advanceTaxPaid2Amount,
        advanceTaxPaidComment: data.advanceTaxPaidComment,
        taxSurchargePaidAmount: data.taxSurchargePaidAmount,
        taxSurchargePaidComment: data.taxSurchargePaidComment,
        interestPaidAmount: data.interestPaidAmount,
        interestPaidComment: data.interestPaidComment,
        total: data.total,
        exemptedIncomeFromSalary: data.exemptedIncomeFromSalary,
        exemptedIncomeFromBusiness: data.exemptedIncomeFromBusiness,
        exemptedAgriculturalIncome: data.exemptedAgriculturalIncome,
        incomeFromProvidentFund: data.incomeFromProvidentFund,
        foreignRemittance: data.foreignRemittance,
        typeOfReceipts1: data.typeOfReceipts1,
        typeOfReceipts2: data.typeOfReceipts2,
        typeOfReceipts3: data.typeOfReceipts3,
        typeOfReceiptsAmount1: data.typeOfReceiptsAmount1,
        typeOfReceiptsAmount2: data.typeOfReceiptsAmount2,
        typeOfReceiptsAmount3: data.typeOfReceiptsAmount3,
        netWealthLastDate: data.netWealthLastDate,
        netWealthLastDateAmount: data.netWealthLastDateAmount,
        giftExpense: data.giftExpense,
        institutionalLiabilities: data.institutionalLiabilities,
        nonInstitutionalLiabilities: data.nonInstitutionalLiabilities,
        otherLiabilities: data.otherLiabilities,
        totalAssetOfBusiness: data.totalAssetOfBusiness,
        lessBusinessLiabilities: data.lessBusinessLiabilities,
        companyName1: data.companyName1,
        companyName2: data.companyName2,
        companyName3: data.companyName3,
        noOfShare1: data.noOfShare1,
        noOfShare2: data.noOfShare2,
        noOfShare3: data.noOfShare3,
        value1: data.value1,
        value2: data.value2,
        value3: data.value3,
        nameOfPartnershipFirm1: data.nameOfPartnershipFirm1,
        nameOfPartnershipFirm2: data.nameOfPartnershipFirm2,
        nameOfPartnershipFirm3: data.nameOfPartnershipFirm3,
        shareOfProfit1: data.shareOfProfit1,
        shareOfProfit2: data.shareOfProfit2,
        shareOfProfit3: data.shareOfProfit3,
        capitalContributed1: data.capitalContributed1,
        capitalContributed2: data.capitalContributed2,
        capitalContributed3: data.capitalContributed3,
        locationDescription1: data.locationDescription1,
        locationDescription2: data.locationDescription2,
        locationDescription3: data.locationDescription3,
        locationDescription4: data.locationDescription4,
        locationDescription5: data.locationDescription5,
        locationValue1: data.locationValue1,
        locationValue2: data.locationValue2,
        locationValue3: data.locationValue3,
        locationValue4: data.locationValue4,
        locationValue5: data.locationValue4,
        agriculturalLocationAndDescription1: data.agriculturalLocationAndDescription1,
        agriculturalLocationAndDescription2: data.agriculturalLocationAndDescription2,
        agriculturalLocationAndDescription3: data.agriculturalLocationAndDescription3,
        agriculturalLocationValue1: data.agriculturalLocationValue1,
        agriculturalLocationValue2: data.agriculturalLocationValue2,
        agriculturalLocationValue3: data.agriculturalLocationValue3,
        shareDebentureUnitCertificate: data.shareDebentureUnitCertificate,
        bondsGovernment: data.bondsGovernment,
        sanchayapatraSavingsCertificate: data.sanchayapatraSavingsCertificate,
        depositPensionScheme: data.depositPensionScheme,
        loansGivenToOthers: data.loansGivenToOthers,
        name: data.name,
        nid: data.nid,
        nidValue: data.nidValue,
        savingDeposit: data.savingDeposit,
        providentFund: data.providentFund,
        otherInvestment1: data.otherInvestment1,
        otherInvestment2: data.otherInvestment2,
        typeOfMotorVehicle1: data.typeOfMotorVehicle1,
        typeOfMotorVehicle2: data.typeOfMotorVehicle2,
        registrationNumber1: data.registrationNumber1,
        registrationNumber2: data.registrationNumber2,
        motorValue1: data.motorValue1,
        motorValue2: data.motorValue2,
        ornaments1: data.ornaments1,
        ornaments2: data.ornaments2,
        furnitureAndElectronic: data.furnitureAndElectronic,
        othersAssets1: data.othersAssets1,
        othersAssets2: data.othersAssets2,
        bankBalance: data.bankBalance,
        cashInHand: data.cashInHand,
        others1: data.others1,
        others2: data.others2,
        assetOutsideBangladesh: data.assetOutsideBangladesh,
      },
    });

    // Revalidate paths if needed
      revalidatePath("/individual-tax-return");
      revalidatePath("/admin/tax-returns");

    return {
      message: "Individual tax return data submitted successfully",
      data: createIndividualTaxReturn,
      success: true,
    };
  } catch (error) {
    console.error(error);
    return {
      message: "An error occurred while submitting individual tax return data.",
      success: false,
    };
  }
}
