import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Judson, Poppins } from "next/font/google";
import "./globals.css";

const bodyFont = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700", "500", "600"],
  variable: "--font-poppins",
});

// Font for titles
const titleFont = Judson({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-judson",
  weight: ["700", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bodyFont.variable} ${titleFont.variable}`}>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
