export const MINIMUM_TAX_OPTIONS = [
  "DHAKA_CHATTOGRAM_CITY_CORPORATION_AREA",
  "OTHER_CITY_CORPORATION_AREA",
  "OTHER_AREA",
];


export const NET_WEALTH_SURCHARGE_OPTIONS = ["YES", "NO"];

export const REPAIR_COLLECTION_OPTIONS = [
  "COMMERCIAL_PROPERTY",
  "NON_COMMERCIAL",
  "RESIDENTIAL_PROPERTY",
  "MIXED_PROPERTY",
];

export const NET_WEALTH_LAST_DATE = [
  "YES",
  "NO_I_AM_A_NEW_TAXPAYER"
];
export const CALCULATE_OPTION = ["Calculate", "ReCalculate"] ;


