// useTaxReturnForm.ts

import { useForm } from "react-hook-form";
import {
  IndividualTaxReturnFormInput,
  individualTaxReturnSchema,
} from "@/app/(site)/individual-tax-return/schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { useFormFields } from "./use-form-fields";
import { useCalculations } from "./use-calculations";

export const useTaxReturnForm = () => {
  const form = useForm<IndividualTaxReturnFormInput>({
    resolver: zodResolver(individualTaxReturnSchema),
    defaultValues: {
      taxpayerName: "John Doe",
      nationalId: "123456789",
      tin: "ABC123",
      circle: "Dhaka North",
      zone: "Zone A",
      assessmentYear: "2022-2023",
      residentialStatus: "RESIDENT",
      assesseeStatus: "INDIVIDUAL",
      specialBenefits: "NONE",
      isParentOfDisabledPerson: false,
      dateOfBirth: new Date("1980-01-01"),
      spouseName: "Jane Doe",
      spouseTin: "XYZ456",
      addressLine1: "123 Main Street",
      addressLine2: "Apartment 4",
      telephone: "01234567890",
      mobile: "01987654321",
      email: "johndoe@example.com",
      employerName: "ABC Corporation",
      businessName: "John's Consulting",
      bin: "BIN123",
      partnersMembersAssociation1: "Partner A",
      partnersMembersAssociation2: "Partner B",
      // Image 2
      statementOfIncomeYearEndedOn: new Date("2022-06-30"),
      incomeFromEmployment: "50000",
      incomeFromRent: "10000",
      incomeFromAgriculture: "5000",
      incomeFromBusiness: "20000",
      incomeFromCapitalGains: "8000",
      incomeFromFinancialAssets: "3000",
      incomeFromOtherSources: "2000",
      shareOfIncomeFromAOP: "1000",
      incomeOfMinor: "500",
      taxableIncomeFromAbroad: "1500",
      totalIncome: "101000",
      totalAmountPayable: "15000",
      minimumTax: "DHAKA_CHATTOGRAM_CITY_CORPORATION_AREA",
      netWealthSurcharge: "1000",
      taxPayable: "10000",
      environmentalSurcharge: "500",
      totalSurcharge: "1500",
      delayInterest: "500",
      grossTaxOnTaxableIncome: "12000",
      netTaxAfterRebate: "10000",
      minimumTaxAmount: "5000",
      // Image 3
      taxDeductedOrCollected: "3000",
      advanceTaxPaid: "2000",
      adjustmentOfTaxRefund: "500",
      taxPaidWithThisReturn: "1000",
      totalTaxPaidAndAdjusted: "6500",
      excessPayment: "1500",
      taxExemptedTaxFreeIncome: "5000",
      listOfDocumentsFurnishedWithThisReturn1: "Income Tax Return",
      listOfDocumentsFurnishedWithThisReturn2: "Salary Slips",
      fatherOrHusband: "John Doe Sr.",
      placeOfSignature: "Dhaka",
      signature: "John Doe",
      dateOfSignature: new Date("2023-04-30"),
      // Image 4
      isIncomeFromEmployment: "YES",
      typeOfEmployment: "GOVERNMENT",
      basicPayGovt: {
        amount: "50000",
        taxExempted: "5000",
        taxable: "45000",
      },
      arrearPayGovt: {
        amount: "2000",
        taxExempted: "200",
        taxable: "1800",
      },
      specialAllowanceGovt: {
        amount: "5000",
        taxExempted: "5000",
        taxable: "0",
      },
      houseRentAllowanceGovt: {
        amount: "10000",
        taxExempted: "10000",
        taxable: "0",
      },
      medicalAllowanceGovt: {
        amount: "2000",
        taxExempted: "2000",
        taxable: "0",
      },
      conveyanceAllowanceGovt: {
        amount: "1000",
        taxExempted: "1000",
        taxable: "0",
      },
      festivalAllowanceGovt: {
        amount: "2000",
        taxable: "2000",
      },
      allowanceForSupportStaffGovt: {
        amount: "1000",
        taxExempted: "1000",
        taxable: "0",
      },
      leaveAllowanceGovt: {
        amount: "1500",
        taxExempted: "1500",
        taxable: "0",
      },
      honorariumRewardGovt: {
        amount: "2000",
        taxExempted: "2000",
        taxable: "0",
      },
      overtimeAllowanceGovt: {
        amount: "1000",
        taxExempted: "1000",
        taxable: "0",
      },
      banglaNoboborshoAllowancesGovt: {
        amount: "500",
        taxExempted: "500",
        taxable: "0",
      },
      interestAccruedProvidentFundGovt: {
        amount: "3000",
        taxExempted: "3000",
        taxable: "0",
      },
      lumpGrantGovt: {
        amount: "2000",
        taxExempted: "2000",
        taxable: "0",
      },
      gratuityGovt: {
        amount: "5000",
        taxExempted: "5000",
        taxable: "0",
      },
      otherAllowanceGovt: {
        amount: "1000",
        taxExempted: "500",
        taxable: "500",
      },
      totalGovt: {
        amount: "85000",
        taxExempted: "33700",
        taxable: "51300",
      },
      // Image 5
      locationDescriptionOwnershipProportionOfProperty:
        "Rented apartment, 50% ownership",
      rentReceivedOrAnnualValue: "12000",
      advanceRentReceived: "2000",
      valueOfAnyBenefit: "500",
      adjustedAdvanceRent: "500",
      vacancyAllowance: "1000",
      totalRentValue: "13000",
      repairCollectionProperty: "RESIDENTIAL_PROPERTY",
      repairCollectionAmount: "3250",
      municipalOrLocalTax: "1000",
      landRevenue: "500",
      interestMortgageCapitalCharge: "1000",
      insurancePremiumPaid: "500",
      otherAllowableDeduction: "500",
      taxpayersSharePercentage: "80",
      taxpayersShareAmount: "10400",
      salesTurnoverReceiptAgriculture: "20000",
      grossProfitFromAgriculture: "16000",
      generalExpensesSellingExpenses: "4000",
      totalAdmissibleDeduction: "7000",
      netIncomeFromRent: "6000",
      netProfitFromAgriculture: "12000",
      // Image 6
      nameOfBusiness: "ABC Traders",
      natureOfBusiness: "Wholesale Trading",
      addressOfBusiness: "456 Commercial Area, Dhaka",
      salesTurnoverReceiptsBusiness: "500000",
      purchase: "300000",
      grossProfitFromBusiness: "200000",
      generalAdministrativeSellingExpenses: "150000",
      badDebtExpense: "10000",
      netProfitFromBusinessIncome: "40000",
      cashInHandAtBank: "50000",
      inventories: "100000",
      fixedAssets: "200000",
      otherAssets: "50000",
      totalAssets: "400000",
      openingCapital: "100000",
      netProfitFromBusinessBalance: "40000",
      withdrawalsInTheIncomeYear: "20000",
      closingCapital: "120000",
      liabilities: "280000",
      totalCapitalsAndLiabilities: "400000",
      incomeFromShareTransferListedCompany: {
        description: "Sale of ABC Company Shares",
        capitalGain: "20000",
        exemptedAmount: "5000",
        taxableAmount: "15000",
      },
      incomeFromCapitalGain2: {
        description: "Sale of XYZ Company Shares",
        capitalGain: "10000",
        exemptedAmount: "2000",
        taxableAmount: "8000",
      },
      incomeFromCapitalGain3: {
        description: "Sale of PQR Company Shares",
        capitalGain: "8000",
        exemptedAmount: "1500",
        taxableAmount: "6500",
      },
      incomeFromCapitalGain4: {
        description: "Sale of LMN Company Shares",
        capitalGain: "6000",
        exemptedAmount: "1000",
        taxableAmount: "5000",
      },
      incomeFromCapitalGain5: {
        description: "Sale of STU Company Shares",
        capitalGain: "4000",
        exemptedAmount: "500",
        taxableAmount: "3500",
      },
      incomeFromCapitaGainsTotal: {
        capitalGain: "48000",
        exemptedAmount: "10000",
        taxableAmount: "38000",
      },
      // Image 7
      shonchoyparta: {
        description: "Sanchayapatra 1",
        balance: "50000",
        interestProfit: "3000",
        sourceTax: "300",
      },
      profitFromShoychoyparta2: {
        description: "Sanchayapatra 2",
        balance: "30000",
        interestProfit: "2000",
        sourceTax: "200",
      },
      profitFromShoychoyparta3: {
        description: "Sanchayapatra 3",
        balance: "25000",
        interestProfit: "1800",
        sourceTax: "180",
      },
      profitFromShoychoyparta4: {
        description: "Sanchayapatra 4",
        balance: "20000",
        interestProfit: "1500",
        sourceTax: "150",
      },
      profitFromShoychoyparta5: {
        description: "Sanchayapatra 5",
        balance: "15000",
        interestProfit: "1200",
        sourceTax: "120",
      },
      profitFromShoychoyparta6: {
        description: "Sanchayapatra 6",
        balance: "12000",
        interestProfit: "1000",
        sourceTax: "100",
      },
      profitFromShoychoyparta7: {
        description: "Sanchayapatra 7",
        balance: "10000",
        interestProfit: "800",
        sourceTax: "80",
      },
      profitFromShoychoyparta8: {
        description: "Sanchayapatra 8",
        balance: "8000",
        interestProfit: "600",
        sourceTax: "60",
      },
      profitFromShoychoyparta9: {
        description: "Sanchayapatra 9",
        balance: "6000",
        interestProfit: "400",
        sourceTax: "40",
      },
      profitFromShoychoyparta10: {
        description: "Sanchayapatra 10",
        balance: "4000",
        interestProfit: "200",
        sourceTax: "20",
      },
      profitFromShoychoypartaTotal: {
        balance: "180000",
        interestProfit: "12500",
        sourceTax: "1250",
      },
      interestFromSecurities: {
        description: "Interest from Government Securities",
        balance: "100000",
        interestProfit: "7000",
        sourceTax: "700",
      },
      profitInterestFromGovtSecurities2: {
        description: "Profit from Govt Securities 2",
        balance: "50000",
        interestProfit: "3500",
        sourceTax: "350",
      },
      profitInterestFromGovtSecurities3: {
        description: "Profit from Govt Securities 3",
        balance: "40000",
        interestProfit: "3000",
        sourceTax: "300",
      },
      profitInterestFromGovtSecurities4: {
        description: "Profit from Govt Securities 4",
        balance: "30000",
        interestProfit: "2500",
        sourceTax: "250",
      },
      profitInterestFromGovtSecurities5: {
        description: "Profit from Govt Securities 5",
        balance: "20000",
        interestProfit: "2000",
        sourceTax: "200",
      },
      profitInterestFromGovtSecurities6: {
        description: "Profit from Govt Securities 6",
        balance: "15000",
        interestProfit: "1500",
        sourceTax: "150",
      },
      profitInterestFromGovtSecurities7: {
        description: "Profit from Govt Securities 7",
        balance: "12000",
        interestProfit: "1200",
        sourceTax: "120",
      },
      profitInterestFromGovtSecurities8: {
        description: "Profit from Govt Securities 8",
        balance: "8000",
        interestProfit: "800",
        sourceTax: "80",
      },
      profitInterestFromGovtSecurities9: {
        description: "Profit from Govt Securities 9",
        balance: "5000",
        interestProfit: "500",
        sourceTax: "50",
      },
      profitInterestFromGovtSecurities10: {
        description: "Profit from Govt Securities 10",
        balance: "3000",
        interestProfit: "300",
        sourceTax: "30",
      },
      profitInterestFromGovtSecuritiesTotal: {
        balance: "283000",
        interestProfit: "19300",
        sourceTax: "1930",
      },
      // Image 8
      lifeInsurancePremium: "10000",
      contributionToDeposit: "5000",
      investmentInGovernmentSecurities: "20000",
      investmentInSecuritiesStock: "15000",
      contributionToProvidentFund: "8000",
      selfAndEmployersContribution: "16000",
      contributionToSuperAnnuationFund: "5000",
      contributionToBenevolentFund: "2000",
      contributionToZakatFund: "1000",
      otherRebatableInvestmentContribution: "3000",
      amountOfTaxRebate: "12000",
      totalAllowableInvestmentContribution: "70000",
      totalIncomeRebateTable: "3030",
      totalAllowableInvestmentRebateTable: "10500",
      taka1000000: "100000",
    },
  });

  const { watch, setValue, getValues, setError, clearErrors } = form;

  const calculations = useCalculations(
    watch,
    setValue,
    getValues,
    setError,
    clearErrors
  );
  const formFields = useFormFields(
    watch,
    setValue,
    getValues,
    setError,
    clearErrors
  );

  return {
    form,
    formFields,
    calculations,
  };
};
